// All searchable commands for the global command palette.
// Each command needs: id, label, description, icon, group, keywords, route.

export const COMMANDS = [
  // ── Navigate ────────────────────────────────────────────────────────────────
  {
    id:          'nav-dashboard',
    label:       'Dashboard',
    description: 'Main operational overview',
    icon:        '🏠',
    group:       'Navigate',
    keywords:    ['home', 'main', 'overview', 'summary', 'briefing'],
    route:       '/dashboard',
  },
  {
    id:          'nav-crew',
    label:       'Operations Board',
    description: 'Daily task board, crew, and operational command center',
    icon:        '👥',
    group:       'Navigate',
    keywords:    ['staff', 'team', 'employees', 'schedule', 'shifts', 'hours', 'labor', 'operations', 'tasks', 'board'],
    route:       '/crew',
  },
  {
    id:          'nav-equipment',
    label:       'Equipment',
    description: 'Fleet list, maintenance logs, and service',
    icon:        '⚙️',
    group:       'Navigate',
    keywords:    ['machines', 'mowers', 'fleet', 'maintenance', 'service', 'repair', 'tools'],
    route:       '/equipment',
  },
  {
    id:          'nav-irrigation',
    label:       'Irrigation',
    description: 'Repairs, head map, and zones',
    icon:        '💧',
    group:       'Navigate',
    keywords:    ['water', 'heads', 'repairs', 'zones', 'pump', 'wet', 'dry', 'leaks'],
    route:       '/irrigation',
  },
  {
    id:          'nav-spray',
    label:       'Spray & Applications',
    description: 'Spray records, calendar, and build sheets',
    icon:        '🌿',
    group:       'Navigate',
    keywords:    ['applications', 'fungicide', 'herbicide', 'pesticide', 'chemicals', 'apply', 'tank'],
    route:       '/spray',
  },
  {
    id:          'nav-disease',
    label:       'Disease Monitoring',
    description: 'Active issues, library, and course map',
    icon:        '🔬',
    group:       'Navigate',
    keywords:    ['pressure', 'monitoring', 'fungal', 'tracking', 'alerts', 'diagnosis'],
    route:       '/disease',
  },
  {
    id:          'nav-nutrition',
    label:       'Plant Nutrition',
    description: 'Soil, tissue, water reports, and recommendations',
    icon:        '🌱',
    group:       'Navigate',
    keywords:    ['fertility', 'soil', 'tissue', 'nutrients', 'fertilizer', 'reports'],
    route:       '/plant-nutrition',
  },
  {
    id:          'nav-cultural',
    label:       'Cultural Practices',
    description: 'Aerification, topdressing, mowing, and rolling calendar',
    icon:        '📅',
    group:       'Navigate',
    keywords:    ['aerification', 'topdress', 'mow', 'roll', 'verticut', 'calendar', 'schedule'],
    route:       '/cultural-practices',
  },
  {
    id:          'nav-inventory',
    label:       'Inventory',
    description: 'Chemicals, parts, fuel, and purchase history',
    icon:        '📦',
    group:       'Navigate',
    keywords:    ['chemicals', 'parts', 'fuel', 'stock', 'supplies', 'purchase', 'low'],
    route:       '/inventory',
  },
  {
    id:          'nav-budget',
    label:       'Budget',
    description: 'Expenses, labor, and cost reports',
    icon:        '💰',
    group:       'Navigate',
    keywords:    ['expenses', 'costs', 'spending', 'financial', 'labor', 'reports'],
    route:       '/budget',
  },
  {
    id:          'nav-activity',
    label:       'Activity Feed',
    description: 'Unified operational timeline',
    icon:        '🕐',
    group:       'Navigate',
    keywords:    ['log', 'history', 'timeline', 'recent', 'audit', 'events'],
    route:       '/activity',
  },
  {
    id:          'nav-settings',
    label:       'Settings',
    description: 'App preferences and course configuration',
    icon:        '⚙️',
    group:       'Navigate',
    keywords:    ['preferences', 'configuration', 'profile', 'course', 'notifications'],
    route:       '/settings',
  },

  // ── Workflows ───────────────────────────────────────────────────────────────
  {
    id:          'wf-ir-repairs',
    label:       'Irrigation Repairs',
    description: 'Open, in-progress, and parts-needed repairs',
    icon:        '💧',
    group:       'Workflows',
    keywords:    ['repair', 'broken', 'leak', 'head', 'valve', 'open', 'fix'],
    route:       '/irrigation',
  },
  {
    id:          'wf-eq-maintenance',
    label:       'Equipment Maintenance Logs',
    description: 'Service records, overdue items, and history',
    icon:        '⚙️',
    group:       'Workflows',
    keywords:    ['service', 'overdue', 'logs', 'maintenance', 'oil', 'filter', 'hours'],
    route:       '/equipment',
  },
  {
    id:          'wf-spray-build',
    label:       'Build Spray Sheet',
    description: 'Plan and schedule a spray application',
    icon:        '🌿',
    group:       'Workflows',
    keywords:    ['build', 'sheet', 'plan', 'create', 'application', 'mix', 'tank'],
    route:       '/spray',
  },
  {
    id:          'wf-disease-library',
    label:       'Disease Library',
    description: 'Turfgrass disease reference and identification',
    icon:        '🔬',
    group:       'Workflows',
    keywords:    ['library', 'reference', 'identify', 'dollar spot', 'pythium', 'brown patch'],
    route:       '/disease',
  },
  {
    id:          'wf-inv-low-stock',
    label:       'Inventory Low Stock',
    description: 'Products approaching or below reorder level',
    icon:        '📦',
    group:       'Workflows',
    keywords:    ['low', 'stock', 'reorder', 'out', 'critical', 'shortage'],
    route:       '/inventory',
  },
  {
    id:          'wf-crew-schedule',
    label:       'Crew Schedule',
    description: 'Weekly shift grid and staff availability',
    icon:        '👥',
    group:       'Workflows',
    keywords:    ['schedule', 'shifts', 'week', 'daily', 'assign', 'staff'],
    route:       '/crew',
  },

  // ── Actions ─────────────────────────────────────────────────────────────────
  {
    id:          'act-calendar',
    label:       'Operations Calendar',
    description: 'View and manage scheduled events',
    icon:        '🗓️',
    group:       'Actions',
    keywords:    ['calendar', 'schedule', 'events', 'planned', 'upcoming'],
    route:       '/cultural-practices',
  },
  {
    id:          'act-upload',
    label:       'Upload Photos',
    description: 'Attach photos to equipment or irrigation records',
    icon:        '📸',
    group:       'Actions',
    keywords:    ['upload', 'photos', 'images', 'attach', 'camera', 'evidence'],
    route:       '/equipment',
  },
  {
    id:          'act-chemical',
    label:       'Chemical Labels & SDS',
    description: 'Safety data sheets and label reference',
    icon:        '⚗️',
    group:       'Actions',
    keywords:    ['sds', 'safety', 'label', 'msds', 'chemical', 'hazard'],
    route:       '/chemical',
  },
  {
    id:          'act-spray-records',
    label:       'Spray Records History',
    description: 'Completed and pending-review spray applications',
    icon:        '🌿',
    group:       'Actions',
    keywords:    ['records', 'history', 'completed', 'spray', 'log', 'applications'],
    route:       '/spray',
  },
]
