export const DEVELOPMENT_TRAINING_BRIEF_SAMPLE = {
  title: 'Greens multi-product training sample',
  sourceType: 'wizard_draft',
  sourceSnapshot: {
    application: {
      name: 'Greens morning application',
      applicationType: 'liquid',
      plannedDate: '2026-08-27',
      startTime: '05:30',
      areas: [{ name: 'Putting greens', acreage: 4 }],
      acreage: 4,
      target: 'Preventive disease management and steady turf growth',
      equipment: 'MultiPro sprayer',
      gpa: 50,
      tankVolume: 300,
      loads: 1,
      operator: 'Assistant superintendent',
      weather: 'Expected 72 F, light wind. Verify actual conditions before application.',
      objective: 'Protect putting greens and support a consistent growth response.',
      expectedResponse: 'Uniform color and growth without visible spray injury.',
      successLooksLike: 'Even coverage and no new disease symptoms in the monitored period.',
      warningSigns: 'Streaking, wilt, discoloration, drift, leaks, or unexpected disease development.',
    },
    products: [
      {
        name: 'Sample Fungicide A',
        category: 'fungicide',
        rate: '0.5',
        rateUnit: 'oz / 1,000 sq ft',
        totalAmount: '87.1',
        totalUnit: 'oz',
        purpose: 'Preventive disease protection listed on the current label.',
        inclusionReason: 'Supports the preventive disease objective for this application.',
        fracGroup: '3',
        labelUrl: 'https://example.invalid/sample-label-a',
        source: 'Development fixture',
        verificationStatus: 'verified',
        ppe: 'Long-sleeved shirt, long pants, shoes plus socks, and chemical-resistant gloves.',
        signalWord: 'Caution',
        reiHours: 12,
      },
      {
        name: 'Sample Wetting Agent B',
        category: 'surfactant',
        rate: '2',
        rateUnit: 'oz / acre',
        totalAmount: '8',
        totalUnit: 'oz',
        purpose: 'Supports uniform water distribution when used according to its label.',
        inclusionReason: 'Included for the manager-approved water-management objective.',
        labelUrl: '',
        source: 'Development fixture',
        verificationStatus: 'unverified',
      },
    ],
    instructions: {
      sprayer: 'MultiPro sprayer',
      waterVolume: '50 gal / acre',
      observations: 'Record actual weather and inspect the application pattern.',
    },
  },
}
